version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        blobdescriptor: inmemory
http:
    addr: :80
    headers:
        X-Content-Type-Options: [nosniff]
    debug:
      addr: localhost:5001
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
